name: Windows Test

on:
  pull_request:
    branches:
      - '4.0.0'
      - 'master'
  push:
    branches:
      - '4.0.0'
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [23]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Erlang
      run: shelltests/win-install-erl.ps1 ${{ matrix.otp_version }}
      id: install_erlang
    - name: Run test
      run: shelltests/wintest.ps1 "${{ steps.install_erlang.outputs.erlpath }}"
